import { AsyncLocalStorage } from 'node:async_hooks';
import { randomUUID } from 'node:crypto';
import type { NextFunction, Request, Response } from 'express';

/** Maximum accepted length for a client-supplied request id. */
const MAX_INCOMING_ID_LENGTH = 128;

/** Per-request context propagated through every async call frame. */
export interface RequestContext {
  requestId: string;
}

/**
 * Storage that carries the request context across async boundaries so any
 * layer (middleware, guards, services, filters) can read the current
 * request id without explicit parameter threading.
 */
export const requestContextStorage = new AsyncLocalStorage<RequestContext>();

/** Returns the request id of the in-flight request, if any. */
export function getRequestId(): string | undefined {
  return requestContextStorage.getStore()?.requestId;
}

/**
 * Express middleware that guarantees every request carries a unique id.
 *
 * A caller-supplied `X-Request-Id` header is reused as-is (truncated check
 * applies) so ids generated by gateways or upstream services correlate
 * end-to-end; otherwise a UUID v4 is generated. The id is echoed back on
 * the response and made available to logging via {@link requestContextStorage}.
 */
export function requestIdMiddleware(
  req: Request,
  res: Response,
  next: NextFunction,
): void {
  const incoming = req.headers['x-request-id'];
  const requestId =
    typeof incoming === 'string' &&
    incoming.trim().length > 0 &&
    incoming.length <= MAX_INCOMING_ID_LENGTH
      ? incoming.trim()
      : randomUUID();

  // Normalize on the request so downstream layers read a single source.
  req.headers['x-request-id'] = requestId;
  res.setHeader('X-Request-Id', requestId);

  requestContextStorage.run({ requestId }, () => next());
}
